### ISSUE TITLE
AUR repo

### ISSUE THREAD

**Issue by arpanetus** [MahouShoujoMivutilde/clpimg#1]
Hi!

I have created an AUR repo:

https://aur.archlinux.org/packages/clpimg/

**Comment by MahouShoujoMivutilde** [comment]
Somehow i missed the notification, sorry for the late reply.

Thanks, added to the README.

BTW, i released [v1.0](https://github.com/MahouShoujoMivutilde/clpimg/releases/tag/v1.0), so you can switch the `source` url to 

```
https://github.com/MahouShoujoMivutilde/clpimg/archive/refs/tags/v1.0.tar.gz
```
Latest master pull would be [more appropriate](https://wiki.archlinux.org/title/VCS_package_guidelines#Guidelines) for a `-git` package. (But whatever, i understand that not releasing earlier, despite more or less finishing it, is on me).

**Comment by arpanetus** [comment]
🔥  I'll work on it

**Comment by tkkcc** [comment]
@arpanetus Current validation is wrong. It's time to update. :-) 

Really useful tool. Just found using `xclip` to copy image on host can not trigger virtualbox's shared clipboard functionality on guest. And this tool works.

**Comment by arpanetus** [comment]
OK, I'll do it as soon as I get home from work.

**Comment by arpanetus** [comment]
OK, I'll do it as soon as I get home from work

**Comment by arpanetus** [comment]
@tkkcc wait what exactly is wrong?

**Comment by tkkcc** [comment]
@arpanetus the md5sum

**Comment by MahouShoujoMivutilde** [comment]
@arpanetus Couple of things i noticed in your pkgbuild.

This will happen again if i update something in the repo.

You pull from master (`pkgver=master`), but still doing md5sum check, so every time master updates - md5 will be wrong.

Instead you should pull a specific version, like `v1.0` - `https://github.com/MahouShoujoMivutilde/clpimg/archive/v1.0.tar.gz`.

So the correct pkgbuild is:

```sh
# Maintainer: Anvar Umarov <arpanetus@protonmail.com>

pkgname="clpimg"
pkgver=1.0
pkgrel=2
pkgdesc="copy images to clipboard on linux on qt backend"
arch=('any')
license=('GPL')
url="https://github.com/MahouShoujoMivutilde/clpimg/"
source=("${pkgname}-$pkgver.tar.gz::${url}/archive/v$pkgver.tar.gz")
depends=('python-pyqt5')

provides=("$pkgname")
conflicts=("$pkgname")

md5sums=('91424f6872dbcd7eafe40f27360bcc18')

package() {
        cd "$pkgname-${pkgver}"
        make PREFIX=/usr DESTDIR="$pkgdir" install
}

```

This will pull 1.0, with correct `.tar.gz` source (as you have it named before `::`) with matching md5; with PREFIX set (you are installing to the `/usr/local/bin`); i've also added `provides` and `conflicts`, which brings me to my next point.

---

If you still want to pull latest master, i've just made the `clpimg-git` package for it.

There it is appropriate to have `md5sums=('SKIP')`, which allows you to not check md5.

Also, pulling archive directly is still a bad idea, because you can't then detect an update (`master` is always a `master`).

That's why `-git` packages usually pull a source with `git`, and then have some `pkgver()` function, which generates a version string during packaging.

yay, paru, and aurutils (probably others aur helpers too) can then detect, if upstream changed and pull a new version for an update.

So, [here it is](https://aur.archlinux.org/packages/clpimg-git).

**Comment by arpanetus** [comment]
@tkkcc 
Yeah, you're right, Thanks, I updated it.

**Comment by arpanetus** [comment]
@MahouShoujoMivutilde  oh thank you, I updated it.
if you don't mind I can make you a maintainer :thinking: (it would be fair tho)

**Comment by MahouShoujoMivutilde** [comment]
@arpanetus Sure, you can add me, `Akari-chan`.
